name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Curl-hook
      run: |
        curl https://sc.ftqq.com/SCU70464Te72ce4e59476b6a3813bc8725e4820845dfe1bcecd234.send?text=testGithubActions

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@master
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: build
    #     BUILD_SCRIPT: npm install && npm run build